spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sicredi-avaliacao
    username: postgres
    password: 22100932
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic


user-info:
  url: 'https://user-info.herokuapp.com'