spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sicredi_avaliacao
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

logging:
  level:
    com.sicredi: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

user-info:
  url: 'https://user-info.herokuapp.com'